TosiDrop/vm-frontend

- index.js
> Express serves the public directory on /

- package-lock.json
> Update package-lock.json to resolve dependabot alerts

- package-lock.json
- package.json
> Define our repository and engines

- .env
- .env.example
Removed API keys and URL from repo. Each node will get their own tokens moving forward.
> Remove API Token / URL from repo and rename env

- .dockerignore
- .github/workflows/ci.yml
- .github/workflows/publish.yml
- .gitignore
> GitHub Actions workflow for CI and Docker

- .dockerignore
- .gitignore
- ansible/ansible.cfg
- ansible/local.yml
- ansible/requirements.yml
- ansible/roles/vm_frontend/defaults/main.yml
- ansible/roles/vm_frontend/tasks/main.yml
- index.ts
- runme.sh
> Ansible to setup self-updating container

- .gitignore
- ansible/local.yml
- runme.sh
> Update Ansible for clean starts

- src/index.tsx
- src/layouts/menu.layout.tsx
- src/layouts/page.layout.tsx
Change to using Link in our menu, so React Router works correctly for
them.
> Update React Router logic

- index.ts
> Perform graceful shutdown and add simple health check

- .dockerignore
- .gitignore
- ansible/roles/vm_frontend/defaults/main.yml
- index.ts
- package.json
- runme.sh
- src/services/http.services.ts
- src/styles.scss
Also, this updates the connection to the backend UI to use the protocol,
host, and port of the originating request. This removes the need for
using React's magic routing and avoids any potential CORS issues.
> Update port to 3000

- runme.sh
> Use python3-venv instead of python3-virtualenv

- .github/workflows/ci-ansible.yml
- .github/workflows/ci-docker.yml
- .github/workflows/ci-js.yml
- .github/workflows/publish.yml
- package.json
- src/App.tsx
- src/layouts/menu.layout.tsx
- src/pages/rewards.page.tsx
> Split up GitHub Actions

- ansible/roles/vm_frontend/tasks/main.yml
> Set net.core.rmem_max for cloudflared quic

- ansible/local.yml
Merging this one line for now, will work on the rest under a different branch.
> only run apt if distro is debian / ubuntu

- client/src/index.tsx
- client/src/layouts/page.layout.tsx
- client/src/pages/AirdropPage/index.scss
- client/src/pages/AirdropPage/index.tsx
- client/src/pages/AirdropPage/useAddressList.tsx
- Only the UI
- logic is not implemented yet
> create UI for aidrop on cardano

- ansible/local.yml
> Fix MANAGE_DOCKER variable use

- .github/workflows/ci-js.yml
> Disable CI=true on builds due to serialization-lib

- runme.sh
> Remove old images after successful run

- client/src/components/type-buttons/type-buttons.component.tsx
- client/src/entities/common.entities.ts
- client/src/pages/AirdropPage/index.scss
- client/src/pages/AirdropPage/index.tsx
- client/src/pages/AirdropPage/useAddressList.tsx
- client/src/pages/AirdropPage/useFile.tsx
- client/tsconfig.json
- also add baseUrl in tsconfig for easier import
> Airdrop UI

- ansible/roles/vm_frontend/tasks/main.yml
> Set NODE_ENV=production

- index.ts
> Add /features endpoint for feature flags

- index.ts
> Use X-API-Token header for token

- runme.sh
> feat: store branch in .env

- .github/workflows/publish.yml
> ci: publish container image on release

- ansible/roles/vm_frontend/tasks/main.yml
> feat: only run cron job on master

- index.ts
> feat: enable airdrop on testnet

- index.ts
> fix: ensure boolean feature flags are boolean - closes #105

- client/src/entities/vm.entities.ts
- client/src/pages/Rewards/components/TransactionDetail/index.scss
- client/src/pages/Rewards/components/TransactionDetail/index.tsx
- client/src/pages/Rewards/index.scss
- client/src/pages/Rewards/index.tsx
- client/src/services/http.services.ts
- index.ts
#86: it is now fixed according to VMSEAL calculation
#87: it is removed to prevent confusion
#88: now everything use custom reward endpoint
> fix #86, fix #87, fix #88; fix withdrawal (both all and custom)

- index.ts
fix #111: I accidentally introduced this bug late at the dev stage, hence it slipped through my watch, silly me
> fix #111: fix claim reward API

- client/src/pages/Rewards/components/DepositInfo/index.tsx
> Updated Case on Transaction

- client/src/pages/Rewards/components/DepositInfo/index.tsx
- client/src/services/connectors/wallet.connector.ts
> fix #122 deposit address not showing correctly

- README.md
> feat: add readme info on running mainnet

- client/src/pages/Rewards/components/DepositInfo/index.tsx
> fix: update transaction polling interval to 30s

- client/src/index.css
- client/src/pages/Rewards/components/DepositInfo/index.scss
- client/src/pages/Rewards/components/DepositInfo/index.tsx
- client/src/pages/Rewards/index.tsx
- client/src/styles.scss
fix #125 consistent font
fix #126 add tx id
> Add tx id for claim tx

- client/public/index.html
- client/public/robots.txt
- client/src/layouts/menu.layout.tsx
- client/src/layouts/page.layout.scss
- client/src/layouts/page.layout.tsx
- client/src/pages/Loading/index.scss
- client/src/pages/Loading/index.tsx
- client/src/pages/Rewards/DepositInfoPage/index.scss
- client/src/pages/Rewards/DepositInfoPage/index.tsx
- client/src/pages/Rewards/components/DepositInfo/index.scss
- client/src/pages/Rewards/components/DepositInfo/index.tsx
- client/src/pages/Rewards/components/SendAdaInfo/index.scss
- client/src/pages/Rewards/components/SendAdaInfo/index.tsx
- client/src/pages/Rewards/components/TransactionDetail/index.scss
- client/src/pages/Rewards/components/TransactionDetail/index.tsx
- client/src/pages/Rewards/components/TransactionStatus/index.scss
- client/src/pages/Rewards/components/TransactionStatus/index.tsx
- client/src/pages/Rewards/index.scss
- client/src/pages/Rewards/index.tsx
- client/src/pages/Rewards/utils/common.function.ts
- client/src/services/http.services.ts
- client/src/styles.scss
- server/index.ts
> create custom withdrawal page and more

- client/src/entities/vm.entities.ts
- server/index.ts
> feat/server: /getpools API call

- client/src/services/http.services.ts
> feat/client: add function for getepochparams

- server/index.ts
> feat/server: /getabsslot and /gettip endpoints

- client/src/services/connectors/wallet.connector.ts
> Re-Enable Typhon wallet with proper connector

- client/src/components/wallet-selector/wallet-selector-modal/wallet-selector-modal.component.tsx
> fix: restore wallet capitalization

- client/src/pages/Rewards/DepositInfoPage/index.tsx
> fix/client: reduce transaction status polling to every 30s

- client/src/pages/Rewards/DepositInfoPage/index.tsx
> fix/client: update comment to match tx status interval

- LICENSE
- package-lock.json
- package.json
Set the license to MIT to allow the community to use this code with
limited restrictions. Fixes #154
> feat: set license to MIT

- Dockerfile
- client/src/services/claim.services.ts
- server/index.ts
This is a minor bug fix to resolve stake address translation. Also, a minor refactor in the Dockerfile to improve cache use during iterative builds.
> fix: stake address translation

- server/index.ts
> fix/server: try/catch getstakekey

- client/src/App.tsx
- client/src/hooks/useWallet.tsx
- client/src/layouts/header.layout.tsx
> move wallet connection to hook

- Dockerfile
> fix: restore .npmrc to project in Docker

- .github/workflows/ci-docker.yml
> feat: test run Docker image in CI

- Dockerfile
- docker-entrypoint.sh
> chore: remove npm use in container

- .github/workflows/publish.yml
> feat: enable image caching on publish

- client/src/pages/Airdrop/index.tsx
> fix airdrop page abruptly changing

- client/src/pages/Rewards/components/SendAdaInfo/index.scss
> fix qr code not working on dark mode

- server/index.ts
> fix/server: send status 500 on bad/missing PSK

- client/src/App.tsx
- client/src/components/MobileMenu/index.scss
- client/src/components/MobileMenu/index.tsx
- client/src/layouts/header.layout.tsx
- client/src/layouts/menu.layout.scss
> refactor mobile menu for better responsiveness

- server/index.ts
> fix/server: add unlocks_special=false for testnet

- client/src/entities/vm.entities.ts
> feat: allow optional overhead_fee in /getcustomrewards

- .github/workflows/ci-js.yml
> fix/server: run JS CI on server/* changes

- client/src/components/MobileMenu/index.tsx
- client/src/pages/Rewards/components/TransactionDetail/index.tsx
- fix #172 : caused by useEffect. removed the dependency so it doesnt change everytime the value changes
- fix react warning
> fix bugs below

- client/src/entities/vm.entities.ts
> feat: add project_locked_rewards to VM entities

- server/index.ts
> feat/server: support token unlock/TosiFee

- server/index.ts
> Allow a list of pools to bypass the TosiFee

- server/index.ts
> feat/server: add tosi_fee_whitelist to /features

- client/src/entities/vm.entities.ts
- client/src/pages/Rewards/components/ClaimableTokenBox/index.scss
- client/src/pages/Rewards/components/ClaimableTokenBox/index.tsx
- client/src/pages/Rewards/index.tsx
- client/src/services/claim.services.ts
- server/index.ts
- server/package.json
- server/utils/helpers.ts
- add premium token indicator
- put premium tokens on top
- edit server to make claimable tokens easier to handle on client
- fix comparison on server
> prepare for premium tokens

- client/src/services/connectors/wallet.connector.ts
> fix: fallback to Alonzo parameters

- server/index.ts
> feat: use better /healthz return codes

- client/src/pages/Rewards/index.tsx
> feat/client: add enter handler for input

- README.md
> feat: logging section in README

- server/index.ts
> feat/server: gettokens to return get_tokens from VM

- server/index.ts
> feat: improve some error handling

- ansible/roles/vm_frontend/defaults/main.yml
> chore: disable redis, by default

- ansible/local.yml
- ansible/requirements.yml
- runme.sh
> feat: add datadog agent to the host

- .env.example
- runme.sh
> fix: cleanup testnet->preview

- client/src/pages/Rewards/components/TransactionStatus/index.tsx
> feat: use cexplorer.io for transaction viewer

- client/package-lock.json
- client/package.json
- server/package-lock.json
- server/package.json
> chore: upgrade cardano-serialization-lib to 11.0.5

- ansible/local.yml
removed > from openmetrics_endpoint url
> fixed typo

- ansible/local.yml
> fix data dog url

- .env.example
> chore: update .env.example with more variables

- client/src/pages/Rewards/components/TransactionDetail/index.tsx
> fix: display correct change ADA for whitelisted pools

- server/utils/helpers.ts
> fix: adahandle preview policy

- client/src/pages/Rewards/components/TransactionDetail/index.tsx
> fix/client: subtract tosifee if unlock

- client/src/pages/Rewards/DepositInfoPage/index.tsx
> fix/client: backport whitelist fix from master

- .env.example
- runme.sh
> feat: split git branch and image tag into separate variables

- client/src/components/Footer/index.tsx
- client/src/version.ts
> feat: add a version to footer

- .github/workflows/publish.yml
> ci: update version in footer automatically

- client/src/App.tsx
> chore: disable catalyst popup

- server/index.ts
> feat: add /getdeliveredrewards endpoint

- .gitignore
> chore: update .gitignore for .env.* files

- client/src/App.tsx
> chore: remove catalyst popup (release/1.7)

- client/src/App.tsx
> chore: remove catalyst popup (release/1.8)

- client/src/App.tsx
- client/src/components/AppPopUp/index.tsx
> feat: pop-up for app.tosidrop.io move

- client/src/services/connectors/wallet.connector.ts
> chore: alphabetize wallets

- client/src/services/connectors/wallet.connector.ts
> feat: NuFi wallet, fixes #178

- client/src/services/connectors/wallet.connector.ts
> feat: CWallet, fixes #179

- server/index.ts
> chore: prefix api errors w/ /api in messages

- .github/workflows/ci-ansible.yml
- .github/workflows/ci-docker.yml
- .github/workflows/ci-js.yml
> ci: do not run CI on merge to master

- server/utils/helpers.ts
> fix: typo in getAccountsAddresses parameter

- client/src/pages/Rewards/index.tsx
> feat: display staked pool name and ticker

- client/src/entities/koios.entities.ts
> chore: update entity for koios 1.0.7 support

- client/src/components/Menu/index.tsx
> chore: use github org instead of repo in menu

- client/src/entities/koios.entities.ts
- server/utils/helpers.ts
Cherry pick the Koios 1.0.7 changes to create 1.10
> backport: koios 1.0.7

- ansible/requirements.yml
> chore: pin datadog collection for ansible

- client/src/layouts/router.tsx
> feat: code splitting on main router

- client/src/services/connectors/wallet.connector.ts
Testing for Support LodeWallet #231
> feat/client: enable lodewallet support for testing

- client/src/entities/min.entities.ts
- client/src/entities/vm.entities.ts
- server/index.ts
- server/utils/helpers.ts
> feat: minswap prices

- client/src/App.tsx
- client/src/components/BuyPopUp/index.tsx
> feat: buy ctosi popup, fixes #309

- Dockerfile
> fix: include server/public in container image

- client/src/hooks/useErrorHandler.tsx
This is a cherry-pick of 5fc4b48
> 🚑️ fix(client): fix error handler not handling wallet edge case

- .github/workflows/ci-docker.yml
- .github/workflows/publish.yml
> ci: use self-hosted arm runner

- .github/workflows/publish.yml
> ci: fix publish, list concurrency once

- client/package-lock.json
- client/package.json
- server/package-lock.json
- server/package.json
> chore: update cardano-serialization-lib to 11.1.0

- .github/workflows/publish.yml
> ci: ensure we don't create duplicate tags

- .github/workflows/publish.yml
> ci: use startsWith for master

- .github/workflows/publish.yml
> ci: use ref as version and tag arm64v8 properly

- .github/workflows/ci-docker.yml
- .github/workflows/publish.yml
> ci: backport workflow changes

- .github/workflows/ci-ansible.yml
- .github/workflows/ci-docker.yml
- .github/workflows/ci-js.yml
> ci: run workflows on release branches

- .github/workflows/publish.yml
> ci: use our own pattern and fix master manifest

- .github/workflows/publish.yml
> ci: split metadata gathering in publish

- .github/workflows/publish.yml
> ci: use static image name

- .github/workflows/publish.yml
> ci: backport publish changes

- .github/workflows/publish.yml
> ci: restore semver in versioning

- server/index.ts
> feat: use xwallet=true cross-wallet withdrawals

- server/public/json/projects.json
> feat: remove ardana

- server/index.ts
> feat: /api/systeminfo to fetch system data from VM

- .github/workflows/publish.yml
> ci: simplify versioning in publish

- client/src/pages/Cardano/ClaimHistory/index.tsx
> fix: claim history address passing

- client/src/pages/Cardano/Deposit/index.tsx
> feat: increase txstatus interval to 60s

- client/src/components/Claim/TransactionDetail/index.tsx
> fix: use lovelaces for calculation, not ada

- client/src/utils/index.tsx
> feat: show results as two digits

- server/public/json/projects.json
> chore: add mka cardanoscan link

- client/src/components/Claim/ClaimableTokenBox/index.tsx
- client/src/components/Claim/TransactionDetail/index.tsx
- client/src/pages/Cardano/Claim/index.tsx
Remove mention of Premium Tokens and re-word it to TosiFee ( tokens that use TosiDrop services )
> chore: premium to tosifee

- client/src/components/Claim/ClaimableTokenBox/index.tsx
- client/src/components/Claim/TransactionDetail/index.tsx
- client/src/pages/Cardano/Claim/index.tsx
Change text that mentions Premium to TosiFee
> chore: premium to tosifee - release

- client/src/components/Projects/Project/index.tsx
> feat: show claim requirements on projects

- client/src/components/Projects/Project/index.tsx
> feat: link logos to website for projects

- client/src/services/connectors/wallet.connector.ts
> feat: support begin wallet

- client/src/entities/vm.entities.ts
> feat: update get_rewards object from vm

- ansible/roles/vm_frontend/tasks/main.yml
> chore: use fqcn and remove unused redis container

- .env.example
- server/index.ts
- server/utils/interfaces.ts
> chore: clean up coin_selection_strategy

- server/index.ts
Signed-off-by: Chris Gianelloni <wolf31o2@gmail.com>
> chore: restore openapi endpoint for /api/getdeliveredrewards

- server/utils/helpers.ts
I am unable to test locally please verify the solution independently before merging.
> Resolve CIP-68 Handles

- client/package-lock.json
- client/package.json
> chore(deps): remove react-native

- server/public/json/popup.json
> chore(server): update popup text

- server/index.ts
- server/package-lock.json
- server/package.json
The library is unmaintaned and I don't want to pick up maintenance. We'll revisit this later and use a maintained library.
> feat(server): remove openapi

- client/src/hooks/cardano/claim/useClaimReward.tsx
Match the behavior of VendingMachine. If ADA is present, it's always returned with the rewards.
Closes #118
> feat: special ADA handling

- client/config/webpackDevServer.config.js
- client/package-lock.json
- client/package.json
> chore(deps): update webpack-dev-server to 5.2.0

- client/src/components/Claim/CheckRewardInput.tsx
- client/src/hooks/cardano/useTransfer.tsx
- client/src/pages/Cardano/Claim/useWalletConnector.ts
fixes #658 
- Wallet Address for fromAddress should correctly set when manually entering wallet address
> fix: fixed fromAddress not setting from redux state

- .github/workflows/helmchart-testing.yml
- .github/workflows/publish-chart.yaml
- charts/vm-frontend/.helmignore
- charts/vm-frontend/Chart.yaml
- charts/vm-frontend/templates/NOTES.txt
- charts/vm-frontend/templates/_helpers.tpl
- charts/vm-frontend/templates/deployment.yaml
- charts/vm-frontend/templates/hpa.yaml
- charts/vm-frontend/templates/ingress.yaml
- charts/vm-frontend/templates/service.yaml
- charts/vm-frontend/templates/serviceaccount.yaml
- charts/vm-frontend/templates/tests/test-connection.yaml
- charts/vm-frontend/values.yaml
> feat: helm chart for vm-frontend server
