TosiDrop/vm-frontend

Dockerfile
index.js
package.json

Move the `npm install` and `cp` to `serve` to the package.json `build`
target, so we can simplify installation.
Simply `npm run build` to build and copy the React app to `serve`.

Perform install and package moves in build

---

index.ts
runme.sh

Adds a secondary /healthz endpoint which will hit the VM API server to
verify if the instance is authenticated. This is a separate endpoint so
we can restrict it and prevent the backend from getting too much traffic
via this call.

Add Cloudflare Pre-shared Key

---

ansible/roles/vm_frontend/tasks/main.yml

Use a random interval within 300 seconds to prevent all instances of the
frontend from updating at the same time. This code will update the
interval on every Ansible run, making the timing on any individual
service irregular.

Splay cron runs

---

runme.sh

This is especially useful for anyone not running on a Ubuntu cloud
instance.

Allow setting DOCKER_USERS in .env

---

ansible/roles/vm_frontend/defaults/main.yml
ansible/roles/vm_frontend/tasks/main.yml
index.ts

Configure a Redis container on the default port and inject connection
constants into the Express server to be used for entity caching.

Add Redis container

---

README.md
ansible/local.yml
runme.sh

Add support for MANAGE_DOCKER in the .env file to allow someone to
diable the management of the Docker daemon, such as if they've already
provided it on the host via other means.

Support MANAGE_DOCKER in .env

---

Dockerfile
docker-entrypoint.sh
index.ts

Create a static /network endpoint and introduce a simple entrypoint
script to allow for easier modifications of the runtime within the
container image.

Add /network endpoint

---

Dockerfile
runme.sh

Use a multistage Dockerfile and reduce the container disk footprint.
```
$ docker images | grep tosi
tosidrop/vm-frontend                                                 latest     e70810a79541   32 minutes ago      1.01GB
tosidrop/vm-frontend                                                 orig       f686fec20376   11 minutes ago      1.63GB
```
This shaves about 630MiB from the final image. :muscle:

Use multistage Dockerfile

---

index.ts

If a path doesn't match an explicit Express route, we should send it to
React to let it handle it with browser-side routing.
Fixes #58

GH-58 Fallback route to React

---

ansible/roles/vm_frontend/tasks/main.yml

Adds the port to the vm-frontend container name, so we differentiate
between different instances easily.

feat: rename vm-frontend container

---

client/src/components/wallet-selector/wallet-selector-modal/wallet-selector-modal.component.tsx

Some key names do not reflect the name of the wallet, use name property instead.

Wallet: use name property instead of key

---

client/src/pages/Rewards/components/SendAdaInfo/index.tsx
client/src/services/connectors/wallet.connector.ts

- it is due to koios updating one of the object key (koios change `coins_per_utxo_word` to `coins_per_utxo_size`)
- add try catch around the area to stop spinner after error

fix wallet not being able to sign

---

server/index.ts

When a TOSIFEE_WHITELIST is defined and a user does not match the
whitelisted pools, set TOSIFEE and unlock project locked tokens.

fix/server: set unlock/fee for non-wl pools

---

client/src/services/claim.ts
client/src/services/common.ts
server/index.ts
server/package-lock.json
server/package.json

Refactor the Express API to serve API routes under `/api` and provide an OpenAPI v3 spec and a Swagger UI, which is available at `/swaggerui`.

feat: refactor API and provide /swaggerui

---

client/src/pages/Rewards/components/TransactionDetail/index.tsx

Remove confusion about the fees by renaming them internally to reflect the source and also simplify the fee display. Use the number of tokens as a multiplier for the transaction fee, to give a better approximation.

feat: update fee calculations

---

server/index.ts

fix: use same name for getdeliveredrewards param

---

client/src/components/Claim/TransactionDetail/index.tsx

This was found to be a bit closer to accurate in practice. It still over estimates slightly, but it's better to be conservative here.

feat: update txCalc per @reqlez testing

---

.github/workflows/publish.yml

This reverts commit 308ae005b320064c47e258ba5970efacce2ae45d.

Revert "ci: fix multi-arch-manifest workaround"

---

client/package-lock.json
client/package.json
server/package-lock.json
server/package.json

These are the dependabot security updates from my fork, as applied today. All of these updates have been running in production in the https://github.com/blinklabs-io/discoin-vm-frontend fork.

chore(deps): dependabot updates

---

.github/dependabot.yml

This will trigger dependabot on any updates, not just critical security updates. This should allow for picking and choosing the individual updates to accept, so they can be tested in isolation. This will simplify the QA process and make it easier for downstream consumers to stay up to date and contribute.

ci: enable dependabot weekly updates

---

.github/workflows/publish.yml

This will allow me to publish images for the downstream blinklabs-io/tosidrop-vm-frontend fork via CI

ci: allow publish workflow for forks

---

client/package.json
client/src/services/claim.ts
client/src/services/common.ts

This allows running the frontend and the server API on separate machines. This will allow us to run the frontend in Cloudflare with the API being hosted by our SPO providers.

feat: support split client and API

---

client/src/components/PopUp/index.tsx
server/public/json/popup.json

feat: new tosidrop popup

---

.github/workflows/ci-docker.yml
.github/workflows/publish.yml

Since we no longer build the frontend in Docker, let's skip the split builds. We don't need it for just the Express backend.

ci(docker): skip self-hosted runners
